#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If php_version doesn't exist, create it. We assume it is the default system one.
ynh_app_setting_set_default --key=php_version --value=$YNH_DEFAULT_PHP_VERSION

ynh_app_setting_set_default --key=php_upload_max_filesize --value=50M
ynh_app_setting_set_default --key=php_post_max_size --value=50M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

#ynh_config_add --template="some_config_file" --destination="$install_dir/some_config_file"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
